src/Ecommerce-Project/Ecommerce.Web/Controllers/ShoppingCardController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.Services.Data.ShoppingCardsServices;
    using Ecommerce.ViewModels.Products;
    using Ecommerce.ViewModels.ShoppingCard;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCardController : BaseController
    {
        private readonly IShoppingCardService shoppingCardService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public ShoppingCardController(IShoppingCardService shoppingCardService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
            : base(userManager, signInManager)
        {
            this.shoppingCardService = shoppingCardService;

            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        [Authorize]
        public async Task AddProductToUserShoppingCard(int productId)
        {
            await this.shoppingCardService.AddProductToUserShoppingCardAsync(this.GetUserId(), productId);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> UserShoppingCard(int currentPage = 1)
        {
            ShoppingCardServiceModel serviceModel = this.shoppingCardService.GetUserShoppingCard(this.GetUserId(), currentPage);

            return this.View(serviceModel);
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Controllers/ShoppingCartController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.Services.Data.ShoppingCardsServices;
    using Ecommerce.ViewModels.Products;
    using Ecommerce.ViewModels.ShoppingCart;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCardService shoppingCardService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public ShoppingCartController(IShoppingCardService shoppingCardService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
            : base(userManager, signInManager)
        {
            this.shoppingCardService = shoppingCardService;

            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        [Authorize]
        public async Task AddProductToUserShoppingCart(int productId)
        {
            await this.shoppingCardService.AddProductToUserShoppingCardAsync(this.GetUserId(), productId);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> UserShoppingCart(int currentPage = 1)
        {
            ShoppingCartServiceModel serviceModel = this.shoppingCardService.GetUserShoppingCard(this.GetUserId(), currentPage);

            return this.View(serviceModel);
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Views/ShoppingCart/UserShoppingCart.cshtml
@model ShoppingCartServiceModel

@{
    ViewData["Title"] = "Your Shopping Card";
    ViewData["ImageHeight"] = 400;
    ViewBag.UserIsInShoppingCard = true;
}

<div class="container-fluid">
    <div class="row">
        <div class="offset-2 col-8" style="margin-right: 35px">
            @if (Model.Products.Any())
            {
                <div class="row mt-4">
                    @foreach (var product in Model.Products)
                    {
                        <div class="col-4 mt-4">
                            <partial name="_ProductCardPartial" model="product" />
                        </div>
                    }
                </div>

                <partial name="_PaginationPartial" model="Model" />
            }
            else
            {

            }
        </div>
    </div>
</div>

<div class="row mt-3">
    <a role="button" class="offset-5 col-2 btn" style="background-color: #D10024; color: white">
        <i class="fa fa-forward" aria-hidden="true"></i>
        Continue
    </a>
</div>

src/Ecommerce-Project/Ecommerce.Web/Views/ShoppingCart/_PaginationPartial.cshtml
@model ShoppingCartServiceModel

@{
    int totalPages = (int)Math.Ceiling((double)(Model.TotalProducts / (double)ProductsServiceModel.ProductsPerPage));
    int startPage = Model.CurrentPage - 3 <= 0 ? 1 : Model.CurrentPage - 3;
    int endPage = Model.CurrentPage + 3 >= totalPages ? totalPages : Model.CurrentPage + 3;

    int firstShowingProductNumber = (Model.CurrentPage - 1) * ProductsServiceModel.ProductsPerPage + 1;
    int lastShowingProductNumber = (Model.CurrentPage - 1) * ProductsServiceModel.ProductsPerPage + Model.Products.Count();

}

<div class="store-filter clearfix">
    <span class="store-qty">Showing @firstShowingProductNumber-@lastShowingProductNumber products</span>
    <ul class="store-pagination">
        @if (Model.CurrentPage != 1)
        {
            <li>
                <a asp-controller="ShoppingCard"
               asp-action="UserShoppingCard"
               asp-route-CurrentPage="@((Model.CurrentPage - 1) < 1 ? Model.CurrentPage = 1 : Model.CurrentPage - 1)">
                    <i class="fa fa-angle-left"></i>
                </a>
            </li>
        }

        @for (int i = startPage; i <= Model.CurrentPage - 1; i++)
        {
            <a asp-controller="ShoppingCard"
           asp-action="UserShoppingCard"
           asp-route-CurrentPage="@i">
            <li>@i</li>
            </a>
        }

        <li class="active">@Model.CurrentPage</li>

        @for (int i = Model.CurrentPage + 1; i <= endPage; i++)
        {
            <a asp-controller="ShoppingCard"
           asp-action="UserShoppingCard"
           asp-route-CurrentPage="@i">
            <li>@i</li>
            </a>
        }

        @if (Model.CurrentPage != totalPages)
        {
            <li>
                <a asp-controller="ShoppingCard"
               asp-action="UserShoppingCard"
               asp-route-CurrentPage="@((Model.CurrentPage + 1) > totalPages ? Model.CurrentPage = totalPages : Model.CurrentPage + 1)">
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        }
    </ul>
</div>