src/Ecommerce-Project/Ecommerce.Web/Controllers/ProductWishlistsController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.Services.Data.ProductWishlistsServices;
    using Ecommerce.ViewModels.Products;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ProductWishlistsController : BaseController
    {
        private readonly IProductWishlistService productWishlistService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

		private readonly ILogger<ProductWishlistsController> logger;

		public ProductWishlistsController(IProductWishlistService productWishlistService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<ProductWishlistsController> logger)
			: base(userManager, signInManager)
		{
			this.productWishlistService = productWishlistService;

			this.userManager = userManager;
			this.signInManager = signInManager;
			
            this.logger = logger;
		}

		[HttpGet]
        [Authorize]
        public async Task<IActionResult> AllForUser()
        {
            IEnumerable<ProductViewModel> products = await this.productWishlistService.AllForUser(this.GetUserId());

            return this.View(products);
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Controllers/ProductsController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.InputModels.Products;
    using Ecommerce.Services.Data.CategoriesServices;
    using Ecommerce.Services.Data.ProductsServices;
    using Ecommerce.Services.Data.ProductWishlistsServices;
    using Ecommerce.ViewModels.Products;
    using Ecommerce.Web.Infrastructure;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private readonly IEnumerable<string> imageExtensions;

        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly IProductWishlistService productWishlistService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
		
        private readonly ILogger<ProductsController> logger;

		public ProductsController(IProductService productService, ICategoryService categoryService, IProductWishlistService productWishlistService, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ILogger<ProductsController> logger)
			: base(userManager, signInManager)
		{
            this.imageExtensions = new List<string>()
            {
                ".jpg",
                ".png",
                ".webp",
                ".gif",
            };

            this.productService = productService;
			this.categoryService = categoryService;
			this.productWishlistService = productWishlistService;
			
            this.signInManager = signInManager;
			this.userManager = userManager;
			
            this.logger = logger;
		}

		[HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ProductFormModel productForm = this.productService.GetProductFormModel();

            return this.View(productForm);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateAsync([FromForm] ProductFormModel productForm)
        {
            foreach (var image in productForm.Images)
            {
                string imageext = Path.GetExtension(image.FileName).ToLower();

                if (!this.imageExtensions.Contains(imageext))
                {
                    ModelState.AddModelError("Images", $"Please upload only the {string.Join(", ", this.imageExtensions)} image files only!");
                    break;
                }
            }

            productForm.UserId = ClaimsPrincipalExtensions.GetUserId(this.User);

            if (!ModelState.IsValid)
            {
                return this.View(productForm);
            }

            await this.productService.CreateAsync(productForm);

            return this.RedirectToAction(nameof(Index), "Home");
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] ProductsServiceModel productsServiceModel)
        {
            ProductsServiceModel productServiceModel = await this.productService.GetProductsServiceModel(productsServiceModel.ProductsSorting, productsServiceModel.SearchNameCriteria, (productsServiceModel.SearchCategory == null ? "all" : productsServiceModel.SearchCategory), productsServiceModel.CurrentPage, ClaimsPrincipalExtensions.GetUserId(this.User));

            return View(productServiceModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, bool isHaveProductReviewError = false)
        {
            ProductDetailsModel productDetails = await this.productService.Details(id, ClaimsPrincipalExtensions.GetUserId(this.User));

            if (isHaveProductReviewError == true)
            {
                ViewData["IsHaveProductReviewError"] = true;
            }
            else
            {
                ViewData["IsHaveProductReviewError"] = false;
            }

            if (this.signInManager.IsSignedIn(this.User))
            {
                ViewData["IsProductIsInUserWishlist"] = this.productWishlistService.IsProductIsInUserWishlist(ClaimsPrincipalExtensions.GetUserId(this.User), id);
            }
            else
            {
                ViewData["IsProductIsInUserWishlist"] = false;
            }

            return this.View(productDetails);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddReviewForProduct(ProductDetailsModel productDetails)
        {
            if (productDetails.ProductReviewServiceModel.AddProductReviewModel.ReviewScale == 0)
            {
                return this.RedirectToAction(nameof(Details), new
                {
                    id = productDetails.ProductReviewServiceModel.AddProductReviewModel.ProductId,
                    isHaveProductReviewError = true,
                });
            }

            await this.productService.AddReviewForProduct(productDetails.ProductReviewServiceModel.AddProductReviewModel);

            return this.RedirectToAction(nameof(Details), new { id = productDetails.ProductReviewServiceModel.AddProductReviewModel.ProductId, });
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Controllers/ShoppingCartController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.Services.Data.ShoppingCardsServices;
    using Ecommerce.ViewModels.Products;
    using Ecommerce.ViewModels.ShoppingCart;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCardService shoppingCardService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public ShoppingCartController(IShoppingCardService shoppingCardService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
            : base(userManager, signInManager)
        {
            this.shoppingCardService = shoppingCardService;

            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        [Authorize]
        public async Task AddProductToUserShoppingCart(int productId)
        {
            await this.shoppingCardService.AddProductToUserShoppingCardAsync(this.GetUserId(), productId);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> UserShoppingCart(int currentPage = 1)
        {
            ShoppingCartServiceModel serviceModel = this.shoppingCardService.GetUserShoppingCard(this.GetUserId(), currentPage);

            return this.View(serviceModel);
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/FooterPartial.cshtml
<footer id="footer">
	<div class="section">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">About Us</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
						<ul class="footer-links">
							<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
							<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
							<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">Categories</h3>
						<ul class="footer-links">
							<li><a href="#">Hot deals</a></li>
							<li><a href="#">Laptops</a></li>
							<li><a href="#">Smartphones</a></li>
							<li><a href="#">Cameras</a></li>
							<li><a href="#">Accessories</a></li>
						</ul>
					</div>
				</div>

				@*<div class="clearfix visible-xs"></div>*@

				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">Information</h3>
						<ul class="footer-links">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Orders and Returns</a></li>
							<li><a href="#">Terms & Conditions</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">Service</h3>
						<ul class="footer-links">
							<li><a href="#">My Account</a></li>
							<li><a href="#">View Cart</a></li>
							<li><a href="#">Wishlist</a></li>
							<li><a href="#">Track My Order</a></li>
							<li><a href="#">Help</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="bottom-footer" class="section">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="footer-payments">
						<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
						<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
					</ul>
					<span class="copyright">
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
					</span>
				</div>
			</div>
		</div>
	</div>
</footer>

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/Newsletter.cshtml
<div id="newsletter" class="section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="newsletter">
					<p>Sign Up for the <strong>NEWSLETTER</strong></p>
					<form>
						<div class="row">
							<input class="input" type="email" placeholder="Enter Your Email">
							<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
						</div>
					</form>
					<ul class="newsletter-follow">
						<li>
							<a href="#"><i class="fab fa-instagram"></i></a>
						</li>
						<li>
							<a href="#"><i class="fab fa-facebook"></i></a>
						</li>
						<li>
							<a href="#"><i class="fab fa-pinterest"></i></a>
						</li>
						<li>
							<a href="#"><i class="fab fa-github"></i></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/_FooterPartial.cshtml
<footer id="footer">
	<div class="section">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">About Us</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
						<ul class="footer-links">
							<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
							<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
							<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">Categories</h3>
						<ul class="footer-links">
							<li><a href="#">Hot deals</a></li>
							<li><a href="#">Laptops</a></li>
							<li><a href="#">Smartphones</a></li>
							<li><a href="#">Cameras</a></li>
							<li><a href="#">Accessories</a></li>
						</ul>
					</div>
				</div>

				@*<div class="clearfix visible-xs"></div>*@

				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">Information</h3>
						<ul class="footer-links">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Orders and Returns</a></li>
							<li><a href="#">Terms & Conditions</a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-3 col-xs-6">
					<div class="footer">
						<h3 class="footer-title">Service</h3>
						<ul class="footer-links">
							<li><a href="#">My Account</a></li>
							<li><a href="#">View Cart</a></li>
							<li><a href="#">Wishlist</a></li>
							<li><a href="#">Track My Order</a></li>
							<li><a href="#">Help</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="bottom-footer" class="section">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="footer-payments">
						<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
						<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
						<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
					</ul>
					<span class="copyright">
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
					</span>
				</div>
			</div>
		</div>
	</div>
</footer>

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/_HeaderPartial.cshtml
@using Ecommerce.Common
@using Ecommerce.Services.Data.ProductWishlistsServices;
@using Ecommerce.Services.Data.ShoppingCardsServices;
@using Microsoft.AspNetCore.Identity;

@inject IProductWishlistService productWishlistService;
@inject IShoppingCardService shoppingCardService;
@inject UserManager<ApplicationUser> userManagaer;
@inject SignInManager<ApplicationUser> signInManager;

<div>
    <div class="row" style="background-color: #2B2D42; height: 40px">
        <div class="container">
            <div class="row">
                <div class="offset-1 col-1 badge" style="margin-top: 10px"><i class="fa fa-phone" style="color: red"></i> &nbsp; @GlobalConstants.Telephone</div>
                <div class="col-1 badge" style="margin-top: 10px"><i class="fa fa-envelope" style="color: red"></i> &nbsp; @GlobalConstants.Email</div>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg" style="background-color: #334; height: 80px">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="navbar-brand d-flex align-items-center" src="./images/ecommerce-icon.png" width=50 height=50 /></a>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white d-flex text-center">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-togglend-0 text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <strong class="text-white">Categories</strong>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="@null" class="dropdown-item">All</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="Smartphones" class="dropdown-item">Smartphones</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="ElectricAppliances" class="dropdown-item">Electric Appliances</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="Gaming" class="dropdown-item">Gaming</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="Sports" class="dropdown-item">Sports</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="Fashion" class="dropdown-item">Fashion</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="Laptops" class="dropdown-item">Laptops</a></li>
                    </ul>
                </li>
                @*<li class="nav-item"><a class="nav-link" role="button"><strong class="text-white">Hot Deals</strong></a></li>*@
                <li class="nav-item"><a asp-controller="Home" asp-action="AboutUs" class="nav-link" role="button"><strong class="text-white">About Us</strong></a></li>
            </ul>

            <div class="col-md-3 clearfix">
                <div class="header-ctn">
                    @if (signInManager.IsSignedIn(this.User))
                    {
                        int wishlistProductsCount = productWishlistService.GetCountOfUserWishlit(userManagaer.GetUserAsync(this.User).Result.Id);
                        int shoppingCardProductsCount = shoppingCardService.GetUserShoppingCard(userManagaer.GetUserAsync(this.User).Result.Id).Products.Count();

                        <div>
                            <a asp-controller="ProductWishlists" asp-action="AllForUser" style="margin-top: 10px" class="nav-link">
                                <i style="color: red" class="fa fa-heart"></i>
                                <span>Wishlist</span>
                                <div class="qty">@wishlistProductsCount</div>
                            </a>
                        </div>
                        <div>
                            <a asp-controller="ShoppingCart" asp-action="UserShoppingCart" style="margin-top: 10px" class="nav-link">
                                <i style="color: red" class="fa fa-shopping-cart"></i>
                                <span>Your Cart</span>
                                <div class="qty">@shoppingCardProductsCount</div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </nav>
</div>

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/slick.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/slick-theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/glider.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">*@
    @*<link rel="stylesheet" href="./css/fontawesome.css">*@
    <link rel="stylesheet" href="~/css/lazy.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.js">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/lib/nouislider/css/nouislider.min.css">
    <link rel="stylesheet" href="~/Ecommerce.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div>
            <partial name="_HeaderPartial" />
        </div>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_NewsletterPartial"/>
    <partial name="_FooterPartial"/>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/popper/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/lazy.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/slick.min.js" asp-append-version="true"></script>
    <script src="~/js/owl.carousel.js" asp-append-version="true"></script>
    <script src="~/js/glider.min.js" asp-append-version="true"></script>
    <script src="~/lib/nouislider/js/nouislider.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/_NewsletterPartial.cshtml
<div id="newsletter" class="section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="newsletter">
					<p>Sign Up for the <strong>NEWSLETTER</strong></p>
					<form>
						<div class="row">
							<input class="input" type="email" placeholder="Enter Your Email">
							<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
						</div>
					</form>
					<ul class="newsletter-follow">
						<li>
							<a href="#"><i class="fa fa-instagram"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-facebook"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-github"></i></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

src/Ecommerce-Project/Ecommerce.Web/Views/Shared/_ProductCardPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@model ProductViewModel
@inject SignInManager<ApplicationUser> signInManager;

<div class="row">
    <div class="products-tabs">
        <div id="tab1" class="tab-pane active">
            <div class="products-slick" data-nav="#slick-nav-1">
                <div class="product">
                    <div class="product-img" style="height: @($"{ViewData["ImageHeight"]}px")">
                        <img src="@Model.Image.Src" alt="">
                        <div class="product-label">
                            @if (Model.AddedTimesToShoppingCart != null)
                            {
                                <span class="sale">x @Model.AddedTimesToShoppingCart</span>
                            }
                            @if (Model.IsHaveDiscount)
                            {
                                <span class="sale">@Model.DiscountPercentage%</span>
                            }
                            @if (DateTime.UtcNow.Subtract(Model.CreatedOn).Days <= 7)
                            {
                                <span class="new">NEW</span>
                            }
                        </div>
                    </div>
                    <div class="product-body">
                        <p class="product-category">@Model.CategoryName</p>
                        <h3 class="product-name"><span class="badge badge-secondary">@Model.Name</span></h3>
                        @if (Model.IsHaveDiscount)
                        {
                            <h4 class="product-price">$@($"{Math.Floor(Model.Price - Model.Price * Model.DiscountPercentage / 100):f2}") <del class="product-old-price">$@($"{Model.Price:f2}")</del></h4>
                        }
                        else
                        {
                            <h4 class="product-price">$@($"{Model.Price:f2}")</h4>
                        }
                        <div class="product-rating">
                            @if (Model.AverageReview != -1)
                            {
                                @for (int i = 1; i <= Model.AverageReview; i++)
                                {
                                    <i class="fa fa-star"></i>
                                }
                                @for (int i = (int)Model.AverageReview + 1; i <= 5; i++)
                                {
                                    <i class="fa fa-star-o"></i>
                                }
                            }
                            else
                            {
                                <span class="badge badge-secondary">No reviews</span>
                            }
                        </div>
                        <div class="product-btns">
                            @if (signInManager.IsSignedIn(this.User))
                            {
                                if (Model.IsProductIsInCurrentUserWishlist)
                                {
                                    <a onclick="RemoveProductFromWishlist(@Model.Id)" role="button" id="remove-product-from-wishlist-@Model.Id" class="remove-from-wishlist col-2"><i style="color: #D10024" class="fa fa-heart"></i><span class="tooltipp">remove from wishlist</span></a>
                                    <a onclick="AddProductToWishlist(@Model.Id)" role="button" id="add-product-to-wishlist-@Model.Id" class="add-to-wishlist col-2 d-none"><i style="color: #D10024" class="fa fa-heart-o"></i><span class="tooltipp">remove from wishlist</span></a>
                                }
                                else
                                {
                                    <a onclick="AddProductToWishlist(@Model.Id)" role="button" id="add-product-to-wishlist-@Model.Id" class="add-to-wishlist col-2"><i style="color: #D10024" class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></a>
                                    <a onclick="RemoveProductFromWishlist(@Model.Id)" role="button" id="remove-product-from-wishlist-@Model.Id" class="remove-from-wishlist col-2 d-none"><i style="color: #D10024" class="fa fa-heart"></i><span class="tooltipp">remove from wishlist</span></a>
                                }
                            }
                            else
                            {
                                <a onclick="AddProductToWishlistForUnsignedUsers()" role="button" id="add-product-to-wishlist" class="add-to-wishlist col-2"><i style="color: #D10024" class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></a>
                            }
                            <a asp-controller="Products" asp-action="Details" asp-route-id="@Model.Id" class="offset-1 col-2 quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></a>
                        </div>
                    </div>
                    @if (ViewBag.UserIsInShoppingCard == null)
                    {
                        <div class="add-to-cart">
                            @if (this.signInManager.IsSignedIn(this.User))
                            {
                                <button onclick="AddProductToUserShoppingCard(@Model.Id)" class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                            }
                            else
                            {
                                <button role="button" asp-area="Identity" asp-page="/Account/Login" class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                            }
                        </div>
                    }
                </div>
            </div>
            <div id="slick-nav-1" class="products-slick-nav"></div>
        </div>
    </div>
</div>