src/Ecommerce-Project/Ecommerce.Web/Controllers/BrandsController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.InputModels.Brands;
    using Ecommerce.Services.Data.BrandsServices;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Data;

    public class BrandsController : BaseController
    {
        private readonly IBrandService brandService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
		
        private readonly ILogger<BrandsController> logger;

		public BrandsController(IBrandService brandService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<BrandsController> logger)
			: base(userManager, signInManager)
		{
			this.brandService = brandService;

			this.userManager = userManager;
			this.signInManager = signInManager;
			
            this.logger = logger;
		}

		[HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return this.View(new BrandFormModel());
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateAsync(BrandFormModel brandFormModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(brandFormModel);
            }

            await this.brandService.CreateAsync(brandFormModel);

            return this.RedirectToAction(nameof(Index), "Home");
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Controllers/CategoriesController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.InputModels.Categories;
    using Ecommerce.Services.Data.CategoriesServices;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : BaseController
    {
        private readonly ICategoryService categoryService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        public CategoriesController(ICategoryService categoryService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
            : base(userManager, signInManager)
        {
            this.categoryService = categoryService;

            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return this.View(new CategoryFormModel());
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateAsync(CategoryFormModel categoryFormModel)
        {
            categoryFormModel.UserId = this.GetUserId();

            if (!ModelState.IsValid)
            {
                return this.View(categoryFormModel);
            }

            await this.categoryService.CreateAsync(categoryFormModel);

            return this.RedirectToAction(nameof(Index), "Home");
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Controllers/ProductsController.cs
namespace Ecommerce.Web.Controllers
{
    using Ecommerce.Data.Models;
    using Ecommerce.InputModels.Products;
    using Ecommerce.Services.Data.CategoriesServices;
    using Ecommerce.Services.Data.ProductsServices;
    using Ecommerce.Services.Data.ProductWishlistsServices;
    using Ecommerce.ViewModels.Products;
    using Ecommerce.Web.Infrastructure;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private readonly IEnumerable<string> imageExtensions;

        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly IProductWishlistService productWishlistService;

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
		
        private readonly ILogger<ProductsController> logger;

		public ProductsController(IProductService productService, ICategoryService categoryService, IProductWishlistService productWishlistService, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ILogger<ProductsController> logger)
			: base(userManager, signInManager)
		{
            this.imageExtensions = new List<string>()
            {
                ".jpg",
                ".png",
                ".webp",
                ".gif",
            };

            this.productService = productService;
			this.categoryService = categoryService;
			this.productWishlistService = productWishlistService;
			
            this.signInManager = signInManager;
			this.userManager = userManager;
			
            this.logger = logger;
		}

		[HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ProductFormModel productForm = this.productService.GetProductFormModel();

            return this.View(productForm);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateAsync([FromForm] ProductFormModel productForm)
        {
            foreach (var image in productForm.Images)
            {
                string imageext = Path.GetExtension(image.FileName).ToLower();

                if (!this.imageExtensions.Contains(imageext))
                {
                    ModelState.AddModelError("Images", $"Please upload only the {string.Join(", ", this.imageExtensions)} image files only!");
                    break;
                }
            }

            productForm.UserId = ClaimsPrincipalExtensions.GetUserId(this.User);

            if (!ModelState.IsValid)
            {
                return this.View(productForm);
            }

            await this.productService.CreateAsync(productForm);

            return this.RedirectToAction(nameof(Index), "Home");
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] ProductsServiceModel productsServiceModel)
        {
            ProductsServiceModel productServiceModel = await this.productService.GetProductsServiceModel(productsServiceModel.ProductsSorting, productsServiceModel.SearchNameCriteria, (productsServiceModel.SearchCategory == null ? "all" : productsServiceModel.SearchCategory), productsServiceModel.CurrentPage, ClaimsPrincipalExtensions.GetUserId(this.User));

            return View(productServiceModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, bool isHaveProductReviewError = false)
        {
            ProductDetailsModel productDetails = await this.productService.Details(id, ClaimsPrincipalExtensions.GetUserId(this.User));

            if (isHaveProductReviewError == true)
            {
                ViewData["IsHaveProductReviewError"] = true;
            }
            else
            {
                ViewData["IsHaveProductReviewError"] = false;
            }

            if (this.signInManager.IsSignedIn(this.User))
            {
                ViewData["IsProductIsInUserWishlist"] = this.productWishlistService.IsProductIsInUserWishlist(ClaimsPrincipalExtensions.GetUserId(this.User), id);
            }
            else
            {
                ViewData["IsProductIsInUserWishlist"] = false;
            }

            return this.View(productDetails);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddReviewForProduct(ProductDetailsModel productDetails)
        {
            if (productDetails.ProductReviewServiceModel.AddProductReviewModel.ReviewScale == 0)
            {
                return this.RedirectToAction(nameof(Details), new
                {
                    id = productDetails.ProductReviewServiceModel.AddProductReviewModel.ProductId,
                    isHaveProductReviewError = true,
                });
            }

            await this.productService.AddReviewForProduct(productDetails.ProductReviewServiceModel.AddProductReviewModel);

            return this.RedirectToAction(nameof(Details), new { id = productDetails.ProductReviewServiceModel.AddProductReviewModel.ProductId, });
        }
    }
}

src/Ecommerce-Project/Ecommerce.Web/Areas/AdminPanel/Views/Admin/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard | Commerce Park";
}

<div class="jumbotron mt-5 mb-5">
    <h1 class="display-4 text-center">Products Dashboard</h1>
    <div class="row mt-4">
        <a class="offset-1 col-4 btn btn-primary">
            Go to products dashboard
        </a>
        <a class="offset-2 col-4 btn btn-primary">
            Go to users dashboard
        </a>
    </div>
    <hr class="my-4">
</div>

src/Ecommerce-Project/Ecommerce.Web/Areas/AdminPanel/Views/Admin/ProductsDashboard.cshtml
@using Ecommerce.Data.Models.Enums
@model ProductsStatisticsServiceModel

@{
    ViewData["Title"] = "Products Dashboard | Commerce Park";
    int i = 0;
}

<div class="jumbotron mt-5 mb-5">
    <h1 class="display-4 text-center">Products Dashboard</h1>
    <div class="row mt-4">
        <span class="offset-2 col-3 badge badge-primary">Total Products: @Model.ProductsCount</span>
        <span class="offset-2 col-3 badge badge-primary">Total Categories: @Model.CategoriesCount</span>
    </div>
    <hr class="my-4">
</div>

<div class="">
    @*<div class="row"> <hr class="mt-4 col-5" /> <h1 class="col-2">&nbsp;Products</h1> <hr class="mt-4 col-5" /> </div>*@
    <h2 class="text-center mb-4 mt-5">Products</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Qantity</th>
                <th scope="col">Status</th>
                <th scope="col">Percentage of Discount</th>
                <th scope="col">Is On Discount</th>
                <th scope="col">Is Deleted</th>
                <th scope="col">Delete / Restore</th>
                <th scope="col">Update</th>
                <th scope="col">Set Discount</th>
                <th scope="col">Set Quantity</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var product in Model.Products)
                {
                    i += 1;
                    <tr class="text-center">
                        <th scope="row">@i</th>
                        @if (product.IsDeleted)
                        {
                            <td>@product.Name</td>
                        }
                        else
                        {
                            <td><a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></td>
                        }
                        <td>@product.Price</td>$
                        <td id="@product.Id-quantity-field">@product.Quantity</td>
                        <td id="@product.Id-status-field">@product.Status</td>
                        <td id="@product.Id-discount-field">@((decimal)product.DiscountPercentage) %</td>
                        <td id="@product.Id-isHaveDiscount-field">@product.IsHaveDiscount</td>
                        <td>@product.IsDeleted</td>
                        @if (product.IsDeleted == true)
                        {
                            <td><a onclick="RestoreProduct(@product.Id)" class="btn btn-primary rounded-pill">Restore</a></td>
                        }
                        else
                        {
                            <td><a onclick="DeleteProduct(@product.Id)" class="btn btn-danger rounded-pill">Delete</a></td>
                        }
                        <td><a role="button" asp-area="AdminPanel" asp-controller="Products" asp-action="Update" asp-route-id="@product.Id" class="btn btn-light rounded-pill">Update</a></td>
                        <td><a role="button" onclick="SetDiscount(@product.Id)" class="btn btn-light rounded-pill">Set New Discount</a></td>
                        <td><a role="button" onclick="SetQuantity(@product.Id)" class="btn btn-light rounded-pill">Set New Quantity</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="mt-5"></div>

    <h2 class="text-center mb-4 mt-5">Categories</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Count of Product</th>
                <th scope="col">Is Deleted</th>
                <th scope="col">Delete / Restore</th>
                <th scope="col">Update</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var category in Model.Categories)
                {
                    i += 1;
                    <tr class="text-center">
                        <th scope="row">@i</th>
                        @if (category.IsDeleted)
                        {
                            <td>@category.Name</td>
                        }
                        else
                        {
                            <td><a asp-area="" asp-controller="Products" asp-action="All" asp-route-SearchCategory="@category.Name.Trim()">@category.Name</a></td>
                        }
                        <td>@category.ProductsCount</td>
                        <td>@category.IsDeleted</td>
                        @if (category.IsDeleted == true)
                        {
                            <td><a onclick="RestoreCategory(@category.Id)" class="btn btn-primary rounded-pill">Restore</a></td>
                        }
                        else
                        {
                            <td><a onclick="DeleteCategory(@category.Id)" class="btn btn-danger rounded-pill">Delete</a></td>
                        }
                        <td><a role="button" asp-area="AdminPanel" asp-controller="Cateories" asp-action="Update" asp-route-id="@category.Id" class="btn btn-light rounded-pill">Update</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<div>
    <h2 class="text-center mb-4 mt-5">Most Expensive Products</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            @{
                i = 0;
                foreach (var product in Model.ProductsOrderedByPriceDescending)
                {
                    i += 1;
                    <tr class="text-center">
                        <th scope="row">@i</th>
                        <td><a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></td>
                        <td>@product.Price</td>$
                    </tr>
                }
            }
        </tbody>
    </table>

    <h2 class="text-center mb-4 mt-5">Cheapest Products</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            @{
                i = 0;
                foreach (var product in Model.ProductsOrderedByPriceAscending)
                {
                    i += 1;
                    <tr class="text-center">
                        <th scope="row">@i</th>
                        <td><a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></td>
                        <td>@product.Price</td>$
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<div class="jumbotron mt-5 mb-5">
    <h1 class="display-4 text-center">Products Action</h1>
    <div class="row mt-4">
        <a class="col-2 btn btn-primary" asp-controller="Products" asp-action="Create"></a>
        <a class="col-2 btn btn-primary" asp-controller="Categories" asp-action="Create"></a>
        <a class="col-2 btn btn-primary" asp-controller="Brands" asp-action="Create"></a>
    </div>
    <hr class="my-4">
</div>

@section Scripts {
    <script>
        function SetDiscount(productId) {
            let discount = prompt("Enter new discount for product", "");
            if (discount != null) {
                discount = discount.replace('%', '');

                $.get('/adminpanel/products/setDiscount?id=' + productId + '&discountAsString=' + discount, (data) => {
                    if (Number(data) == 0) {
                        $('#' + productId + '-isHaveDiscount-field').text('False');
                    } else {
                        $('#' + productId + '-isHaveDiscount-field').text('True');
                    }

                    $('#' + productId + '-discount-field').text(Number.parseFloat(data).toFixed(2) + ' %');
                });
            }
        }

        function SetQuantity(productId) {
            let quantity = prompt("Enter new quantity for product", "");
            if (quantity != null) {
                quantity = quantity.replace(' ', '');

                $.get('/adminpanel/products/setQuantity?id=' + productId + '&quantityAsString=' + quantity, (data) => {
                    if (Number(data) == 0) {
                        $('#' + productId + '-status-field').text('Unavailable');
                    } else {
                        $('#' + productId + '-status-field').text('Available');
                    }

                    $('#' + productId + '-quantity-field').text(Number.parseFloat(data).toFixed(0));
                });
            }
        }

        function DeleteProduct(productId) {
            let result = window.confirm("Are you sure?")

            if (result) {
                $.get('/adminpanel/products/apidelete?id=' + productId, (data) => {
                    window.location.reload();
                });
            }
        }

        function RestoreProduct(productId) {
            let result = window.confirm("Are you sure?")

            if (result) {
                $.get('/adminpanel/products/apirestore?id=' + productId, (data) => {
                    window.location.reload();
                });
            }
        }

        function DeleteCategory(categoryId) {
            let result = window.confirm("Are you sure?")

            if (result) {
                $.get('/adminpanel/categories/apidelete?id=' + categoryId, (data) => {
                    window.location.reload();
                });
            }
        }

        function RestoreCategory(categoryId) {
            let result = window.confirm("Are you sure?")

            if (result) {
                $.get('/adminpanel/categories/apirestore?id=' + categoryId, (data) => {
                    window.location.reload();
                });
            }
        }
    </script>
}

src/Ecommerce-Project/Ecommerce.Web/Areas/AdminPanel/Views/Admin/UsersDashboard.cshtml
@model UsersStatistsicsServiceModel

@{
    ViewData["Title"] = "Users Dashboard | Commerce Park";
    int i = 0;
}

<div class="jumbotron mt-5 mb-5">
    <h1 class="display-4 text-center">Users Dashboard</h1>
    <div class="row mt-4">
        <span class="offset-2 col-3 badge badge-primary">Total Users: @Model.UsersCount</span>
        <span class="offset-2 col-3 badge badge-primary">Total Administrators: @Model.AdminsCount</span>
    </div>
    <hr class="my-4">
</div>

<div>
    <h2 class="text-center mb-4 mt-5">Users</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Email</th>
                <th scope="col">Email Confirmed</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Orders Created Count</th>
                <th scope="col">Reviews Created Count</th>
                <th scope="col">Is Deleted</th>
                <th scope="col">Delete / Restore</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var user in Model.Users)
                {
                    i += 1;
                    <tr class="text-center">
                        <th scope="row">@i</th>
                        <td>@user.FullName</td>
                        <td>@user.Email</td>
                        <td>@user.EmailConfirmed</td>
                        <td>@user.PhoneNumber</td>
                        <td>@user.OrdersCount</td>
                        <td>@user.ReviewsCount</td>
                        <td>@user.IsDeleted</td>
                        @if (user.IsDeleted == true)
                        {
                            <td><a onclick="RestoreUser(@user.Id)" class="btn btn-primary rounded-pill">Restore</a></td>
                        }
                        else
                        {
                            <td><a onclick="DeleteUser(@user.Id)" class="btn btn-danger rounded-pill">Delete</a></td>
                        }
                    </tr>
                }
            }
        </tbody>
    </table>

    <h2 class="text-center mb-4 mt-5">Administrators</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Email</th>
                <th scope="col">Email Confirmed</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Orders Created Count</th>
                <th scope="col">Reviews Created Count</th>
                <th scope="col">Roles</th>
            </tr>
        </thead>
        <tbody>
            @{
                i = 0;
                foreach (var admin in Model.Admins)
                {
                    i += 1;
                    <tr class="text-center">
                        <th scope="row">@i</th>
                        <td>@admin.FullName</td>
                        <td>@admin.Email</td>
                        <td>@admin.EmailConfirmed</td>
                        <td>@admin.PhoneNumber</td>
                        <td>@admin.OrdersCount</td>
                        <td>@admin.ReviewsCount</td>
                        <td>@(string.Join(", ", admin.Roles.Select(r => r.Name)))</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script>
        function DeleteUser(id) {
            $.get('adminarea/admin/deleteuser?id=' + id, (data) => {
                window.location.reload();
            })
        }

        function RestoreUser(id) {
            $.get('adminarea/admin/restoreuser?id=' + id, (data) => {
                window.location.reload();
            })
        }
    </script>
}